### ISSUE TITLE
Commandline Argument: -l

### ISSUE THREAD

**Issue by hightower5** [uptoratlen/gsArchivPDFDownloader#5] opened 2021-04-29 10:52 UTC
Hello,

the argument "-l" doesn't work for me.

`d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.5>python gsArchivPDFDownloader.py -l
2021-04-29 12:47:45:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-04-29 12:47:45:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-04-29 12:47:45:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-04-29 12:47:51:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [hightower/******]
2021-04-29 12:47:54:[INFO ] Trying now to download the latest version for (Year,Editions) (curMonth/Year)=>(2021, 4) (4/2021)
Traceback (most recent call last):
  File "d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.5\gsArchivPDFDownloader.py", line 236, in <module>
    filenamepattern_download, filenamepattern_local = filename_modification(
  File "d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.5\gsArchivPDFDownloader.py", line 27, in filename_modification
    for filenamerepl in (("<ausgabe>", f"{edition_month:02d}"), ("<jahr>", str(edition_jahr))):
ValueError: Unknown format code 'd' for object of type 'str'`

Best regards.

**Comment by uptoratlen** [comment] 2021-04-29 12:11
I think I know the issue, based on the log. Could oyu only post me the current json snip of the "latestdownload": [
            {
                "year": .....
            }
        ]
(please do not post any credentials. In the  time I will fix it anyway. Sorry for this.

**Comment by hightower5** [comment] 2021-04-29 12:49
2021-04-29 14:45:36:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-04-29 14:45:36:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-04-29 14:45:36:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-04-29 14:45:45:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxx/******]
2021-04-29 14:45:48:[INFO ] Trying now to download the latest version for (Year,Editions) (curMonth/Year)=>(2021, 4) (4/2021)

**Comment by uptoratlen** [comment] 2021-04-29 15:11
I was a bit misunderstanding, I wanted to have the section of the gs.json. But it turned out, that my testing was not correct. In the end I downloaded only the last edition, but the error was seen in case more than one was downloaded. 
Anyway, I tried to get a fix for that, and a more strict handling of the type. I tested the version and it looked fine for me now. 
**If you kindly download the latest version of gsArchivPDFDownloader.py and give it a second try I would be very thankful**. And before that please make sure that the gs.json is in format :
        "latestdownload": [
            {
                "year": "2021",
                "edition": "3"
            }
        ],
Mind the " arround the numbers. The format was not changed , but just to be confirmed on that.

**Comment by hightower5** [comment] 2021-04-29 16:39
Hi,

did you upload a new version? Wrong version?

```
d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6>python gsArchivPDFDownloader.py -l
2021-04-29 18:47:17:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-04-29 18:47:17:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-04-29 18:47:17:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-04-29 18:47:23:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxxxxxxxxxxxxx/************************]
2021-04-29 18:47:25:[INFO ] Trying now to download the latest version for (Year,Editions) (curMonth/Year)=>(2021, 4) (4/2021)
Traceback (most recent call last):
  File "d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 297, in <module>
    filenamepattern_download, filenamepattern_local = filename_modification(
  File "d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 51, in filename_modification
    for filenamerepl in (("<ausgabe>", f"{edition_month:02d}"), ("<jahr>", edition_jahr)):
ValueError: Unknown format code 'd' for object of type 'str'
```

I took the default setting:

```
"latestdownload": [
            {
                "year": "2021",
                "edition": "3"
            }
        ],
```

**Comment by uptoratlen** [comment] 2021-04-29 18:52
OMG - sorry I missed the point. Now I saw it......will report back...omg....shame on me....

**Comment by uptoratlen** [comment] 2021-04-29 20:02
The issue was caused by your absolute right of setting "edition2d": "Yes". As said I stumbled across the int/str issue mentioned before , so I thought it is that issue. But reading your first report I should have seen "ValueError:" not "TypeError". The fix for a upcoming 0.6 is not bad and helpful, but the real issue is caused by wrong handling of the var.
After reading your nicely formatted log (your 2nd post)  it hit me, and than it was not much work.
Next time I will add some automatic tests to prevent such issues. Sorry for the additional time wasted for you. 
Could you download the latest version I named 0.5b and try it again?

**Comment by hightower5** [comment] 2021-04-29 23:11
There must be a small error. The downloaded file will not be moved.

```
d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.5b>python gsArchivPDFDownloader.py -l
2021-04-30 01:03:20:[INFO ] gsArchivPDFDownloader Version:0.5b
2021-04-30 01:03:20:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-04-30 01:03:20:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-04-30 01:03:20:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-04-30 01:03:26:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxxxxxxxxxxxxx/************************]
2021-04-30 01:03:28:[INFO ] Trying now to download the latest version for (Editions/Year) (curMonth/curYear)=>(4/2021) (4/2021)
2021-04-30 01:03:28:[INFO ] Process Download for 'C:\Daten\Gamestar-Archive/2021/GameStar Nr. 04_2021.pdf'
2021-04-30 01:03:33:[INFO ] Try now download of : Jahr 2021 and Ausgabe 4 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=4
2021-04-30 01:03:48:[INFO ] Download done successful
2021-04-30 01:03:50:[ERROR] Exception:[WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Daten\\Gamestar-Archive/GameStar_Nr._4_2021.pdf' -> 'C:\\Daten\\Gamestar-Archive/2021/GameStar Nr. 04_2021.pdf'
Traceback (most recent call last):
  File "d:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.5b\gsArchivPDFDownloader.py", line 145, in download_edition
    os.rename(f"{user_data[0]['downloadtarget']}/{filenamepattern_download}",
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Daten\\Gamestar-Archive/GameStar_Nr._4_2021.pdf' -> 'C:\\Daten\\Gamestar-Archive/2021/GameStar Nr. 04_2021.pdf'

```

**Comment by uptoratlen** [comment] 2021-04-29 23:52
Based on the feedback the original topic is solved . The new error is moved to a new issue. Closing this one. Thx for the effort of testing.

**Closed as completed by uptoratlen** 2021-04-29 23:52 UTC
Labels: bug
